spring:
  application:
    name: transmitter

  mssql:
    reference:
      url: ${mssql.reference.url}
      database: ${mssql.reference.database}
      user: ${mssql.reference.user}
      password: ${mssql.reference.password}
    monitor:
      url: ${mssql.monitor.url}
      database: ${mssql.monitor.database}
      user: ${mssql.monitor.user}
      password: ${mssql.monitor.password}

  kafka:
    bootstrap-servers: ${kafka.bootstrap.servers}
    consumer:
      group-id: ${kafka.group-id}
      key-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      enable-auto-commit: false
      auto-offset-reset: earliest
      fetch.min.bytes: 1048576
      session.timeout.ms: 30000
      reconnect.backoff.ms: 1000
      reconnect.backoff.max.ms: 10000
      partition.assignment.strategy: org.apache.kafka.clients.consumer.CooperativeStickyAssignor
        